services:
  api:
    image: api
    restart: unless-stopped
    build: .
    ports:
      - '${PORT}:${PORT}'

  palworld-wiki-db:
    extends:
      file: compose-db.yml
      service: palworld-wiki-db
  # pgadmin4:
  #   extends:
  #     file: compose-db.yml
  #     service: pgadmin4
