services:
  palworld-wiki-db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - '${PG_PORT}:5432' # Map port 5432 in the container to port 5432 on the Docker host.

  pgadmin:
    image: dpage/pgadmin4:8.2
    depends_on:
      - palworld-wiki-db
    restart: unless-stopped
    # environment:
    # PG Admin seems to be ignoring this env variables. Contrary to what the docs says.
    #   PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_DEFAULT_EMAIL}
    #   PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_DEFAULT_PASSWORD}
    ports:
      - '${PG_ADMIN_PORT}:80' # Map port 80 in the container to port 5050 in the Docker host.
