services:
  palworld_wiki_backend:
    image: jrposada/palworld-wiki-backend:latest
    restart: unless-stopped
    volumes:
      - frontend_data:/app/data

  palworld_wiki_frontend:
    image: jrposada/palworld-wiki-frontend:latest
    restart: unless-stopped
    volumes:
      - backend_data:/app/data
    ports:
      - '${VITE_PORT}:${VITE_PORT}'

  palworld_wiki_db:
    extends:
      file: compose.db.yml
      service: palworld_wiki_db

  pgadmin4:
    extends:
      file: compose.db.yml
      service: pgadmin4

volumes:
  backend_data:
    external: false
  frontend_data:
    external: false
  pgadmin4_data:
    external: false
  postgres_data:
    external: false
